language: nodejs
node_js: 8.1.2
cache:
  yarn: true
script:
  - yarn test
before_deploy:
  - yarn publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
