language: nodejs
cache:
  yarn: true
before_install:
  - nvm install stable
  - nvm use stable
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test
before_deploy:
  - yarn publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master
